import machine
pin1=machine.Pin(1, machine.Pin.OUT)
pin2=machine.Pin(2, machine.Pin.OUT)
pin3=machine.Pin(3, machine.Pin.OUT)
pin4=machine.Pin(4, machine.Pin.OUT)
pin5=machine.Pin(5, machine.Pin.OUT)
pin6=machine.Pin(6, machine.Pin.OUT)
pin7=machine.Pin(7, machine.Pin.OUT)
pin8=machine.Pin(8, machine.Pin.OUT)
pin9=machine.Pin(9, machine.Pin.OUT)
pin10=machine.Pin(10, machine.Pin.OUT)
pin11=machine.Pin(11, machine.Pin.OUT)
pin12=machine.Pin(12, machine.Pin.OUT)
pin13=machine.Pin(13, machine.Pin.OUT)

pin8.value(1)
